room_names_and_desc = {
    "Hall of Whispers": "The walls gossip about your failures… and they never forget.",
    "Cursed Pantry": "Food so rotten even the rats leave polite notes.",
    "Skeleton Ballroom": "Bony dancers practice their eternal waltz, no partner required.",
    "Bloody Chapel": "Candles flicker over altars long past any holy inspection.",
    "Spider's Antechamber": "Webs so thick even spiders need a machete.",
    "Torturer's Library": "Books scream silently, the margins soaked in irony… and blood.",
    "Forgotten Crypt": "Where the dead nap and occasionally judge your life choices.",
    "Ghoul's Pantry": "Dinner served cold, with a side of gnawing teeth.",
    "Mirror of Regret": "Shows not your face, but the awful decisions behind it.",
    "Pit of Endless Echoes": "Every scream echoes… like a bad punchline in a void.",
    "Haunted Armory": "Armor moves by itself, but don’t worry—it’s a pacifist.",
    "Alchemist's Demise": "Potions bubble ominously; the owner did not survive the taste test.",
    "Chamber of Bones": "The décor is skeletal, the vibe is judgmental.",
    "The Rotting Garden": "Plants die slowly, plotting revenge on anyone who enters.",
    "Bloodstained Hall": "Every stain tells a story… none of them are cheerful.",
    "Sorcerer's Attic": "Books levitate, cursing anyone who sneezes.",
    "The Wailing Corridor": "The walls cry, complain, and occasionally snicker at you.",
    "Damp Mausoleum": "Moist, moldy, and mildly offended by your presence.",
    "Fleshbound Cellar": "The walls breathe… mostly to mock your panic.",
    "Necromancer's Study": "Skulls, feathers, and bad decisions float lazily in candlelight.",
    "Vampire's Lounge": "Velvet chairs, stale wine, and a hint of existential dread.",
    "Ghastly Pantry": "Spoiled cheese sighs sadly when opened.",
    "Cryptic Nursery": "Rattles echo, rocking chairs move themselves, babies are optional.",
    "Coffin Corridor": "Line up, lie down, and try not to join permanently.",
    "Skeletal Spa": "Steam rises, bones creak, relaxation is mandatory.",
    "Mad Altar": "Candles scream when lit, incense argues with your nose.",
    "Rusty Dungeon": "Chains rattle like sarcastic applause.",
    "Goblin's Restroom": "It smells worse than any curse could describe.",
    "Infernal Kitchen": "Cooking utensils attempt self-defense.",
    "Plague Cellar": "The rats wear tiny masks. You should too.",
    "Weeping Library": "Books cry for attention, mostly yours.",
    "Cursed Throne": "Sit if you dare, get judgment in return.",
    "Fungus Ballroom": "Mold waltzes elegantly, spores applause.",
    "Specter's Closet": "Hangers float, coats whisper secrets you didn’t ask for.",
    "Bloody Pantry": "Ingredients scream when touched, and some might bite.",
    "Ghoul Gym": "Weights lift themselves and mock your weak arms.",
    "Tortured Workshop": "Tools are alive, slightly resentful, and sharp.",
    "Haunted Hallway": "Floors creak and ceilings moan; a classic welcome.",
    "Shadow Kitchen": "Shadows stir the pot, seasoning with spite.",
    "Necrotic Nursery": "Toys move, dolls judge, crib squeaks like a scream.",
    "Corpse Courtyard": "Grass grows over bones, giving it a chic aesthetic.",
    "Eternal Cellar": "Every step downward feels like a decade.",
    "Ghastly Gallery": "Paintings stare… and occasionally wink at your misery.",
    "Wraith Workshop": "Ghostly hands fix broken things… poorly.",
    "Vile Vault": "Treasure gleams, curses gleam brighter.",
    "Plagued Pantry": "Ingredients rot faster than your hope.",
    "The Murmuring Chamber": "Whispers and giggles, mostly at your expense.",
    "Bone Attic": "Dusty skulls line the walls, judging your taste in decor.",
    "Rotting Study": "Books smell like despair and mildew.",
    "Eerie Alcove": "Shadows gather here for tea and idle gossip.",
    "Flesh Garden": "Plants seem to twitch when you blink.",
    "Spectral Hall": "Ghosts politely step aside… sometimes."
}

junk_items = {
    "Rusty Teapot": "Once boiled water, now mostly memories and rust flakes.",
    "Moth-Eaten Cloak": "Guaranteed to add at least two ghostly inches to your silhouette.",
    "Broken Pocket Watch": "Time travels here, but only backwards.",
    "Old Boots": "Odor adds +2 intimidation, style -5.",
    "Cracked Goblet": "Holds liquids, though it might pour them into another dimension.",
    "Foul Candle": "Burns slowly… and complains the entire time.",
    "Dusty Teacup": "Holds tea, dust, and existential disappointment.",
    "Rusty Spoon": "Perfect for stirring potions… or grudges.",
    "Cracked Mirror": "Shows what you fear most: unpaid taxes and spiders.",
    "Soggy Scroll": "Contains a prophecy… or just soggy paper.",
    "Cobwebbed Bottle": "Contains liquid… or dreams. Hard to tell.",
    "Tiny Cage": "Holds… something, but nobody wants to find out.",
    "Mismatched Socks": "A fashion statement, possibly cursed.",
    "Old Shoe": "Smells of adventure and regret.",
    "Faded Banner": "Once heralded greatness, now mostly mildew."
}

normal_items = {
    "Faded Map": "Shows somewhere you’ve never wanted to go… probably.",
    "Tarnished Locket": "Holds memories… mostly regret and dust.",
    "Porcelain Doll Head": "Eyes follow you. Not creepy at all.",
    "Tiny Music Box": "Plays tunes of sorrow with a hint of sarcasm.",
    "Cracked Compass": "Always points somewhere vaguely ominous.",
    "Patchwork Hat": "Adds +1 style, -3 dignity.",
    "Jar of Glowworms": "Tiny light bulbs with an attitude problem.",
    "Tattered Diary": "Someone’s embarrassing secrets, minus context.",
    "Skeletal Key": "Opens a lock… eventually. Or just mocks you.",
    "Miniature Chair": "For fairies, or really cruel pets.",
    "Glass Eye": "Someone lost one, now it’s your problem.",
    "Faintly Glowing Rock": "Mildly magical, mostly judgmental.",
    "Jar of Pickled Eyeballs": "Oddly flavored, and slightly judgmental.",
    "Faded Banner": "Once waved in glory, now mostly mildew.",
    "Cracked Goblet": "Holds liquids… occasionally something interesting."
}

high_value_items = {
    "Phoenix Feather": "Warm to the touch and slightly judgmental.",
    "Elixir of Forgetfulness": "Makes you forget… minor regrets or tax debts.",
    "Cursed Coin": "Worth more than it should… at a cost.",
    "Miniature Dragon Skull": "Ages well, looks terrifying, slightly valuable.",
    "Potion of Eternal Bubblegum": "Chews forever… or until reality breaks.",
    "Ring of Mild Inconvenience": "Annoys foes subtly; priceless to collectors.",
    "Gilded Teaspoon": "Shiny enough to blind a greedy merchant.",
    "Spectral Candle": "Burns without wax, scent of existential dread included.",
    "Vial of Moonlight": "Captures light that refuses to stay in bottles.",
    "Ancient Music Box": "Plays the lament of a king nobody remembers.",
    "Obsidian Dice": "Roll them and gamble with fate itself.",
    "Golden Feather Quill": "Writes stories that sometimes come true.",
    "Enchanted Snail Shell": "Slowly reveals secrets to those patient enough.",
    "Crystal Jar of Whispering Winds": "Contains voices of forgotten adventurers.",
    "Bag of Trickster Dust": "Makes a mess, causes laughter, and occasionally wealth."
}

simple_weapons = {
    "Rusty Dagger": "Sharp-ish, mostly rusty, probably tetanus-certified.",
    "Cracked Sword": "Cuts slightly better than wet noodles.",
    "Wooden Club": "Solid, heavy, and smells faintly of regret.",
    "Bent Spear": "Thrown once, bent forever, still kind of useful.",
    "Splintered Stick": "Primitive, yet disturbingly effective.",
    "Broken Shovel": "For digging graves or faces, your choice.",
    "Iron Pipe": "Simple, effective, slightly dented.",
    "Jagged Knife": "Cuts worse than it looks… mostly skin.",
    "Knotted Whip": "Hits like a rope, occasionally like a fist.",
    "Shattered Chair Leg": "Improvise, adapt, survive, or just trip."
}

crafted_weapons = {
    "Rusty Mace": "Guaranteed to dent something, maybe your ego.",
    "Chipped Axe": "Cuts wood, maybe a toe.",
    "Spiked Shield": "Defensive until you hit yourself with it.",
    "Heavy Chain": "Good for swinging, dragging, or tripping enemies.",
    "Blunted Hammer": "Hits hard, leaves bruises, not pride.",
    "Spiked Flail": "Swings unpredictably; exciting for all nearby.",
    "Wooden Staff": "Martial arts optional, bruising guaranteed.",
    "Iron Rod": "Pointy enough for persuasion, blunt enough for threats.",
    "Jagged Club": "Handcrafted pain with a hint of malice.",
    "Reinforced Bat": "Extra nails, extra bruises, extra regret."
}

legendary_weapons = {
    "Masterwork Longsword": "Shiny, balanced, slightly judgmental of amateurs.",
    "Polished Warhammer": "Blows that make statues nervous.",
    "Engraved Battle Axe": "Cuts with style and a hint of ego.",
    "Spiked Morningstar": "Rolls into combat like a little doom.",
    "Knightly Halberd": "For those who like pointy things at a distance.",
    "Ornate Flanged Mace": "Looks fancy, hits messy.",
    "Reinforced Iron Club": "Simple yet terrifyingly efficient.",
    "Weighted Quarterstaff": "For disciplined strikes and dramatic flair.",
    "Hand-Forged Dagger": "Sharp, elegant, slightly smug.",
    "Veteran’s Polearm": "Old, seasoned, and dangerously opinionated."
}
